# Generated by Django 4.2.16 on 2025-01-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBackFormsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("text", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SpeechToEval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker", models.CharField(max_length=255)),
                ("speaker_email", models.CharField(max_length=255)),
                ("speech_name", models.CharField(max_length=255)),
                ("pathway_challenge", models.CharField(max_length=255)),
                ("feedback_form", models.CharField(max_length=255)),
            ],
        ),
    ]
